### ISSUE TITLE
Not implemented LayoutBeginColumn

### ISSUE THREAD

**Issue by juh9870** [zeozeozeo/microui-go#1]
Text control calls `ctx.LayoutBeginColumn()`, which is not implemented https://github.com/zeozeozeo/microui-go/blob/main/layout.go#L20 
Were there some porblem with commented out line?

**Comment by zeozeozeo** [comment]
I think I just forgot about it :P

**Comment by juh9870** [comment]
Oh, ok, so just uncommenting it should be fine?
I want to port microui to another language, but my C knowledge is nil, so I'm very grateful to you for creating this Go port that I can understand!

**Comment by zeozeozeo** [comment]
> Oh, ok, so just uncommenting it should be fine? I want to port microui to another language, but my C knowledge is nil, so I'm very grateful to you for creating this Go port that I can understand!

Yeah, I think it should work. By the way, the port has some bugs, so it probably won't work that well :^)

**Comment by juh9870** [comment]
Oh? Is there a list of known bugs? But okay, I will try to read C then

**Comment by zeozeozeo** [comment]
> Oh? Is there a list of known bugs? But okay, I will try to read C then

Mouse input doesn't work, that's probably an issue in InHoverRoot (maybe because of `ContainerStack`?)
https://github.com/zeozeozeo/microui-go/blob/97bf953d203744daf5663308cc7e1fa9fb9b954d/controls.go#L14-L26

**Comment by juh9870** [comment]
I see. Will try to reference C code as much as possible during my port then, thanks for the info!

**Comment by zeozeozeo** [comment]
Will close this now, this port is considered complete thanks to @Zyko0 :)
